package com.black.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FctCase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CaseID
     *
     * @mbggenerated
     */
    private String caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CompanyID
     *
     * @mbggenerated
     */
    private String companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CompanyName
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CustomerID
     *
     * @mbggenerated
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CustomerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.IDCardNumber
     *
     * @mbggenerated
     */
    private String idcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CustomerMobilePhone
     *
     * @mbggenerated
     */
    private String customermobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.CustomerTelPhone
     *
     * @mbggenerated
     */
    private String customertelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.ProductID
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.ProductName
     *
     * @mbggenerated
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.ContractDate
     *
     * @mbggenerated
     */
    private Date contractdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.ContractMoney
     *
     * @mbggenerated
     */
    private BigDecimal contractmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.OverDueStartDate
     *
     * @mbggenerated
     */
    private Date overduestartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.OverDueMoney
     *
     * @mbggenerated
     */
    private BigDecimal overduemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.OverDueDays
     *
     * @mbggenerated
     */
    private Integer overduedays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.OverDueFlag
     *
     * @mbggenerated
     */
    private Integer overdueflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_case.Remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fct_case
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.ID
     *
     * @return the value of fct_case.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.ID
     *
     * @param id the value for fct_case.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CaseID
     *
     * @return the value of fct_case.CaseID
     *
     * @mbggenerated
     */
    public String getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CaseID
     *
     * @param caseid the value for fct_case.CaseID
     *
     * @mbggenerated
     */
    public void setCaseid(String caseid) {
        this.caseid = caseid == null ? null : caseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CompanyID
     *
     * @return the value of fct_case.CompanyID
     *
     * @mbggenerated
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CompanyID
     *
     * @param companyid the value for fct_case.CompanyID
     *
     * @mbggenerated
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CompanyName
     *
     * @return the value of fct_case.CompanyName
     *
     * @mbggenerated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CompanyName
     *
     * @param companyname the value for fct_case.CompanyName
     *
     * @mbggenerated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CustomerID
     *
     * @return the value of fct_case.CustomerID
     *
     * @mbggenerated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CustomerID
     *
     * @param customerid the value for fct_case.CustomerID
     *
     * @mbggenerated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CustomerName
     *
     * @return the value of fct_case.CustomerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CustomerName
     *
     * @param customername the value for fct_case.CustomerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.IDCardNumber
     *
     * @return the value of fct_case.IDCardNumber
     *
     * @mbggenerated
     */
    public String getIdcardnumber() {
        return idcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.IDCardNumber
     *
     * @param idcardnumber the value for fct_case.IDCardNumber
     *
     * @mbggenerated
     */
    public void setIdcardnumber(String idcardnumber) {
        this.idcardnumber = idcardnumber == null ? null : idcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CustomerMobilePhone
     *
     * @return the value of fct_case.CustomerMobilePhone
     *
     * @mbggenerated
     */
    public String getCustomermobilephone() {
        return customermobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CustomerMobilePhone
     *
     * @param customermobilephone the value for fct_case.CustomerMobilePhone
     *
     * @mbggenerated
     */
    public void setCustomermobilephone(String customermobilephone) {
        this.customermobilephone = customermobilephone == null ? null : customermobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.CustomerTelPhone
     *
     * @return the value of fct_case.CustomerTelPhone
     *
     * @mbggenerated
     */
    public String getCustomertelphone() {
        return customertelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.CustomerTelPhone
     *
     * @param customertelphone the value for fct_case.CustomerTelPhone
     *
     * @mbggenerated
     */
    public void setCustomertelphone(String customertelphone) {
        this.customertelphone = customertelphone == null ? null : customertelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.ProductID
     *
     * @return the value of fct_case.ProductID
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.ProductID
     *
     * @param productid the value for fct_case.ProductID
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.ProductName
     *
     * @return the value of fct_case.ProductName
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.ProductName
     *
     * @param productname the value for fct_case.ProductName
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.ContractDate
     *
     * @return the value of fct_case.ContractDate
     *
     * @mbggenerated
     */
    public Date getContractdate() {
        return contractdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.ContractDate
     *
     * @param contractdate the value for fct_case.ContractDate
     *
     * @mbggenerated
     */
    public void setContractdate(Date contractdate) {
        this.contractdate = contractdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.ContractMoney
     *
     * @return the value of fct_case.ContractMoney
     *
     * @mbggenerated
     */
    public BigDecimal getContractmoney() {
        return contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.ContractMoney
     *
     * @param contractmoney the value for fct_case.ContractMoney
     *
     * @mbggenerated
     */
    public void setContractmoney(BigDecimal contractmoney) {
        this.contractmoney = contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.OverDueStartDate
     *
     * @return the value of fct_case.OverDueStartDate
     *
     * @mbggenerated
     */
    public Date getOverduestartdate() {
        return overduestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.OverDueStartDate
     *
     * @param overduestartdate the value for fct_case.OverDueStartDate
     *
     * @mbggenerated
     */
    public void setOverduestartdate(Date overduestartdate) {
        this.overduestartdate = overduestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.OverDueMoney
     *
     * @return the value of fct_case.OverDueMoney
     *
     * @mbggenerated
     */
    public BigDecimal getOverduemoney() {
        return overduemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.OverDueMoney
     *
     * @param overduemoney the value for fct_case.OverDueMoney
     *
     * @mbggenerated
     */
    public void setOverduemoney(BigDecimal overduemoney) {
        this.overduemoney = overduemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.OverDueDays
     *
     * @return the value of fct_case.OverDueDays
     *
     * @mbggenerated
     */
    public Integer getOverduedays() {
        return overduedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.OverDueDays
     *
     * @param overduedays the value for fct_case.OverDueDays
     *
     * @mbggenerated
     */
    public void setOverduedays(Integer overduedays) {
        this.overduedays = overduedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.OverDueFlag
     *
     * @return the value of fct_case.OverDueFlag
     *
     * @mbggenerated
     */
    public Integer getOverdueflag() {
        return overdueflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.OverDueFlag
     *
     * @param overdueflag the value for fct_case.OverDueFlag
     *
     * @mbggenerated
     */
    public void setOverdueflag(Integer overdueflag) {
        this.overdueflag = overdueflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_case.Remarks
     *
     * @return the value of fct_case.Remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_case.Remarks
     *
     * @param remarks the value for fct_case.Remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_case
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", caseid=").append(caseid);
        sb.append(", companyid=").append(companyid);
        sb.append(", companyname=").append(companyname);
        sb.append(", customerid=").append(customerid);
        sb.append(", customername=").append(customername);
        sb.append(", idcardnumber=").append(idcardnumber);
        sb.append(", customermobilephone=").append(customermobilephone);
        sb.append(", customertelphone=").append(customertelphone);
        sb.append(", productid=").append(productid);
        sb.append(", productname=").append(productname);
        sb.append(", contractdate=").append(contractdate);
        sb.append(", contractmoney=").append(contractmoney);
        sb.append(", overduestartdate=").append(overduestartdate);
        sb.append(", overduemoney=").append(overduemoney);
        sb.append(", overduedays=").append(overduedays);
        sb.append(", overdueflag=").append(overdueflag);
        sb.append(", remarks=").append(remarks);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}