package com.black.model;

import java.io.Serializable;

public class FctCustomercontract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerID
     *
     * @mbggenerated
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.IDCardNumber
     *
     * @mbggenerated
     */
    private String idcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerMobilePhone
     *
     * @mbggenerated
     */
    private String customermobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerTelPhone
     *
     * @mbggenerated
     */
    private String customertelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerHomeAddress
     *
     * @mbggenerated
     */
    private String customerhomeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerFamilyAddress
     *
     * @mbggenerated
     */
    private String customerfamilyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.CustomerCompanyAddress
     *
     * @mbggenerated
     */
    private String customercompanyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.ContractName
     *
     * @mbggenerated
     */
    private String contractname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.ContractRelationShip
     *
     * @mbggenerated
     */
    private String contractrelationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.ContractMobilePhone
     *
     * @mbggenerated
     */
    private String contractmobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customercontract.Remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fct_customercontract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.ID
     *
     * @return the value of fct_customercontract.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.ID
     *
     * @param id the value for fct_customercontract.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerID
     *
     * @return the value of fct_customercontract.CustomerID
     *
     * @mbggenerated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerID
     *
     * @param customerid the value for fct_customercontract.CustomerID
     *
     * @mbggenerated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerName
     *
     * @return the value of fct_customercontract.CustomerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerName
     *
     * @param customername the value for fct_customercontract.CustomerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.IDCardNumber
     *
     * @return the value of fct_customercontract.IDCardNumber
     *
     * @mbggenerated
     */
    public String getIdcardnumber() {
        return idcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.IDCardNumber
     *
     * @param idcardnumber the value for fct_customercontract.IDCardNumber
     *
     * @mbggenerated
     */
    public void setIdcardnumber(String idcardnumber) {
        this.idcardnumber = idcardnumber == null ? null : idcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerMobilePhone
     *
     * @return the value of fct_customercontract.CustomerMobilePhone
     *
     * @mbggenerated
     */
    public String getCustomermobilephone() {
        return customermobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerMobilePhone
     *
     * @param customermobilephone the value for fct_customercontract.CustomerMobilePhone
     *
     * @mbggenerated
     */
    public void setCustomermobilephone(String customermobilephone) {
        this.customermobilephone = customermobilephone == null ? null : customermobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerTelPhone
     *
     * @return the value of fct_customercontract.CustomerTelPhone
     *
     * @mbggenerated
     */
    public String getCustomertelphone() {
        return customertelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerTelPhone
     *
     * @param customertelphone the value for fct_customercontract.CustomerTelPhone
     *
     * @mbggenerated
     */
    public void setCustomertelphone(String customertelphone) {
        this.customertelphone = customertelphone == null ? null : customertelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerHomeAddress
     *
     * @return the value of fct_customercontract.CustomerHomeAddress
     *
     * @mbggenerated
     */
    public String getCustomerhomeaddress() {
        return customerhomeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerHomeAddress
     *
     * @param customerhomeaddress the value for fct_customercontract.CustomerHomeAddress
     *
     * @mbggenerated
     */
    public void setCustomerhomeaddress(String customerhomeaddress) {
        this.customerhomeaddress = customerhomeaddress == null ? null : customerhomeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerFamilyAddress
     *
     * @return the value of fct_customercontract.CustomerFamilyAddress
     *
     * @mbggenerated
     */
    public String getCustomerfamilyaddress() {
        return customerfamilyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerFamilyAddress
     *
     * @param customerfamilyaddress the value for fct_customercontract.CustomerFamilyAddress
     *
     * @mbggenerated
     */
    public void setCustomerfamilyaddress(String customerfamilyaddress) {
        this.customerfamilyaddress = customerfamilyaddress == null ? null : customerfamilyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.CustomerCompanyAddress
     *
     * @return the value of fct_customercontract.CustomerCompanyAddress
     *
     * @mbggenerated
     */
    public String getCustomercompanyaddress() {
        return customercompanyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.CustomerCompanyAddress
     *
     * @param customercompanyaddress the value for fct_customercontract.CustomerCompanyAddress
     *
     * @mbggenerated
     */
    public void setCustomercompanyaddress(String customercompanyaddress) {
        this.customercompanyaddress = customercompanyaddress == null ? null : customercompanyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.ContractName
     *
     * @return the value of fct_customercontract.ContractName
     *
     * @mbggenerated
     */
    public String getContractname() {
        return contractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.ContractName
     *
     * @param contractname the value for fct_customercontract.ContractName
     *
     * @mbggenerated
     */
    public void setContractname(String contractname) {
        this.contractname = contractname == null ? null : contractname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.ContractRelationShip
     *
     * @return the value of fct_customercontract.ContractRelationShip
     *
     * @mbggenerated
     */
    public String getContractrelationship() {
        return contractrelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.ContractRelationShip
     *
     * @param contractrelationship the value for fct_customercontract.ContractRelationShip
     *
     * @mbggenerated
     */
    public void setContractrelationship(String contractrelationship) {
        this.contractrelationship = contractrelationship == null ? null : contractrelationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.ContractMobilePhone
     *
     * @return the value of fct_customercontract.ContractMobilePhone
     *
     * @mbggenerated
     */
    public String getContractmobilephone() {
        return contractmobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.ContractMobilePhone
     *
     * @param contractmobilephone the value for fct_customercontract.ContractMobilePhone
     *
     * @mbggenerated
     */
    public void setContractmobilephone(String contractmobilephone) {
        this.contractmobilephone = contractmobilephone == null ? null : contractmobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customercontract.Remarks
     *
     * @return the value of fct_customercontract.Remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customercontract.Remarks
     *
     * @param remarks the value for fct_customercontract.Remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customercontract
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customerid=").append(customerid);
        sb.append(", customername=").append(customername);
        sb.append(", idcardnumber=").append(idcardnumber);
        sb.append(", customermobilephone=").append(customermobilephone);
        sb.append(", customertelphone=").append(customertelphone);
        sb.append(", customerhomeaddress=").append(customerhomeaddress);
        sb.append(", customerfamilyaddress=").append(customerfamilyaddress);
        sb.append(", customercompanyaddress=").append(customercompanyaddress);
        sb.append(", contractname=").append(contractname);
        sb.append(", contractrelationship=").append(contractrelationship);
        sb.append(", contractmobilephone=").append(contractmobilephone);
        sb.append(", remarks=").append(remarks);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}