package com.black.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FctOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.ContractID
     *
     * @mbggenerated
     */
    private String contractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.EmployeeID
     *
     * @mbggenerated
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.EmployeeName
     *
     * @mbggenerated
     */
    private String employeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.CustomerID
     *
     * @mbggenerated
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.CustomerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.IDCardNumber
     *
     * @mbggenerated
     */
    private String idcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.BankCardNumber
     *
     * @mbggenerated
     */
    private String bankcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.BankName
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.StoreID
     *
     * @mbggenerated
     */
    private String storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.StoreName
     *
     * @mbggenerated
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.ProductID
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.ProductName
     *
     * @mbggenerated
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.ContractMoney
     *
     * @mbggenerated
     */
    private BigDecimal contractmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.AlreadyPeriods
     *
     * @mbggenerated
     */
    private Integer alreadyperiods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.ContractPeriods
     *
     * @mbggenerated
     */
    private Integer contractperiods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.RepaymentStartDate
     *
     * @mbggenerated
     */
    private Date repaymentstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.RepaymentEndDate
     *
     * @mbggenerated
     */
    private Date repaymentenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.RepaymentDay
     *
     * @mbggenerated
     */
    private Integer repaymentday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.OverDueDays
     *
     * @mbggenerated
     */
    private Integer overduedays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.AdvanceMoney
     *
     * @mbggenerated
     */
    private BigDecimal advancemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.RepaymentMoney
     *
     * @mbggenerated
     */
    private BigDecimal repaymentmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.EntrustStartDate
     *
     * @mbggenerated
     */
    private Date entruststartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.EntrustEndDate
     *
     * @mbggenerated
     */
    private Date entrustenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.EntrustCompanyName
     *
     * @mbggenerated
     */
    private String entrustcompanyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_order.Remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fct_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.ID
     *
     * @return the value of fct_order.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.ID
     *
     * @param id the value for fct_order.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.ContractID
     *
     * @return the value of fct_order.ContractID
     *
     * @mbggenerated
     */
    public String getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.ContractID
     *
     * @param contractid the value for fct_order.ContractID
     *
     * @mbggenerated
     */
    public void setContractid(String contractid) {
        this.contractid = contractid == null ? null : contractid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.EmployeeID
     *
     * @return the value of fct_order.EmployeeID
     *
     * @mbggenerated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.EmployeeID
     *
     * @param employeeid the value for fct_order.EmployeeID
     *
     * @mbggenerated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.EmployeeName
     *
     * @return the value of fct_order.EmployeeName
     *
     * @mbggenerated
     */
    public String getEmployeename() {
        return employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.EmployeeName
     *
     * @param employeename the value for fct_order.EmployeeName
     *
     * @mbggenerated
     */
    public void setEmployeename(String employeename) {
        this.employeename = employeename == null ? null : employeename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.CustomerID
     *
     * @return the value of fct_order.CustomerID
     *
     * @mbggenerated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.CustomerID
     *
     * @param customerid the value for fct_order.CustomerID
     *
     * @mbggenerated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.CustomerName
     *
     * @return the value of fct_order.CustomerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.CustomerName
     *
     * @param customername the value for fct_order.CustomerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.IDCardNumber
     *
     * @return the value of fct_order.IDCardNumber
     *
     * @mbggenerated
     */
    public String getIdcardnumber() {
        return idcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.IDCardNumber
     *
     * @param idcardnumber the value for fct_order.IDCardNumber
     *
     * @mbggenerated
     */
    public void setIdcardnumber(String idcardnumber) {
        this.idcardnumber = idcardnumber == null ? null : idcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.BankCardNumber
     *
     * @return the value of fct_order.BankCardNumber
     *
     * @mbggenerated
     */
    public String getBankcardnumber() {
        return bankcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.BankCardNumber
     *
     * @param bankcardnumber the value for fct_order.BankCardNumber
     *
     * @mbggenerated
     */
    public void setBankcardnumber(String bankcardnumber) {
        this.bankcardnumber = bankcardnumber == null ? null : bankcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.BankName
     *
     * @return the value of fct_order.BankName
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.BankName
     *
     * @param bankname the value for fct_order.BankName
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.StoreID
     *
     * @return the value of fct_order.StoreID
     *
     * @mbggenerated
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.StoreID
     *
     * @param storeid the value for fct_order.StoreID
     *
     * @mbggenerated
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid == null ? null : storeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.StoreName
     *
     * @return the value of fct_order.StoreName
     *
     * @mbggenerated
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.StoreName
     *
     * @param storename the value for fct_order.StoreName
     *
     * @mbggenerated
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.ProductID
     *
     * @return the value of fct_order.ProductID
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.ProductID
     *
     * @param productid the value for fct_order.ProductID
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.ProductName
     *
     * @return the value of fct_order.ProductName
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.ProductName
     *
     * @param productname the value for fct_order.ProductName
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.ContractMoney
     *
     * @return the value of fct_order.ContractMoney
     *
     * @mbggenerated
     */
    public BigDecimal getContractmoney() {
        return contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.ContractMoney
     *
     * @param contractmoney the value for fct_order.ContractMoney
     *
     * @mbggenerated
     */
    public void setContractmoney(BigDecimal contractmoney) {
        this.contractmoney = contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.AlreadyPeriods
     *
     * @return the value of fct_order.AlreadyPeriods
     *
     * @mbggenerated
     */
    public Integer getAlreadyperiods() {
        return alreadyperiods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.AlreadyPeriods
     *
     * @param alreadyperiods the value for fct_order.AlreadyPeriods
     *
     * @mbggenerated
     */
    public void setAlreadyperiods(Integer alreadyperiods) {
        this.alreadyperiods = alreadyperiods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.ContractPeriods
     *
     * @return the value of fct_order.ContractPeriods
     *
     * @mbggenerated
     */
    public Integer getContractperiods() {
        return contractperiods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.ContractPeriods
     *
     * @param contractperiods the value for fct_order.ContractPeriods
     *
     * @mbggenerated
     */
    public void setContractperiods(Integer contractperiods) {
        this.contractperiods = contractperiods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.RepaymentStartDate
     *
     * @return the value of fct_order.RepaymentStartDate
     *
     * @mbggenerated
     */
    public Date getRepaymentstartdate() {
        return repaymentstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.RepaymentStartDate
     *
     * @param repaymentstartdate the value for fct_order.RepaymentStartDate
     *
     * @mbggenerated
     */
    public void setRepaymentstartdate(Date repaymentstartdate) {
        this.repaymentstartdate = repaymentstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.RepaymentEndDate
     *
     * @return the value of fct_order.RepaymentEndDate
     *
     * @mbggenerated
     */
    public Date getRepaymentenddate() {
        return repaymentenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.RepaymentEndDate
     *
     * @param repaymentenddate the value for fct_order.RepaymentEndDate
     *
     * @mbggenerated
     */
    public void setRepaymentenddate(Date repaymentenddate) {
        this.repaymentenddate = repaymentenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.RepaymentDay
     *
     * @return the value of fct_order.RepaymentDay
     *
     * @mbggenerated
     */
    public Integer getRepaymentday() {
        return repaymentday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.RepaymentDay
     *
     * @param repaymentday the value for fct_order.RepaymentDay
     *
     * @mbggenerated
     */
    public void setRepaymentday(Integer repaymentday) {
        this.repaymentday = repaymentday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.OverDueDays
     *
     * @return the value of fct_order.OverDueDays
     *
     * @mbggenerated
     */
    public Integer getOverduedays() {
        return overduedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.OverDueDays
     *
     * @param overduedays the value for fct_order.OverDueDays
     *
     * @mbggenerated
     */
    public void setOverduedays(Integer overduedays) {
        this.overduedays = overduedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.AdvanceMoney
     *
     * @return the value of fct_order.AdvanceMoney
     *
     * @mbggenerated
     */
    public BigDecimal getAdvancemoney() {
        return advancemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.AdvanceMoney
     *
     * @param advancemoney the value for fct_order.AdvanceMoney
     *
     * @mbggenerated
     */
    public void setAdvancemoney(BigDecimal advancemoney) {
        this.advancemoney = advancemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.RepaymentMoney
     *
     * @return the value of fct_order.RepaymentMoney
     *
     * @mbggenerated
     */
    public BigDecimal getRepaymentmoney() {
        return repaymentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.RepaymentMoney
     *
     * @param repaymentmoney the value for fct_order.RepaymentMoney
     *
     * @mbggenerated
     */
    public void setRepaymentmoney(BigDecimal repaymentmoney) {
        this.repaymentmoney = repaymentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.EntrustStartDate
     *
     * @return the value of fct_order.EntrustStartDate
     *
     * @mbggenerated
     */
    public Date getEntruststartdate() {
        return entruststartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.EntrustStartDate
     *
     * @param entruststartdate the value for fct_order.EntrustStartDate
     *
     * @mbggenerated
     */
    public void setEntruststartdate(Date entruststartdate) {
        this.entruststartdate = entruststartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.EntrustEndDate
     *
     * @return the value of fct_order.EntrustEndDate
     *
     * @mbggenerated
     */
    public Date getEntrustenddate() {
        return entrustenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.EntrustEndDate
     *
     * @param entrustenddate the value for fct_order.EntrustEndDate
     *
     * @mbggenerated
     */
    public void setEntrustenddate(Date entrustenddate) {
        this.entrustenddate = entrustenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.EntrustCompanyName
     *
     * @return the value of fct_order.EntrustCompanyName
     *
     * @mbggenerated
     */
    public String getEntrustcompanyname() {
        return entrustcompanyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.EntrustCompanyName
     *
     * @param entrustcompanyname the value for fct_order.EntrustCompanyName
     *
     * @mbggenerated
     */
    public void setEntrustcompanyname(String entrustcompanyname) {
        this.entrustcompanyname = entrustcompanyname == null ? null : entrustcompanyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_order.Remarks
     *
     * @return the value of fct_order.Remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_order.Remarks
     *
     * @param remarks the value for fct_order.Remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contractid=").append(contractid);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", employeename=").append(employeename);
        sb.append(", customerid=").append(customerid);
        sb.append(", customername=").append(customername);
        sb.append(", idcardnumber=").append(idcardnumber);
        sb.append(", bankcardnumber=").append(bankcardnumber);
        sb.append(", bankname=").append(bankname);
        sb.append(", storeid=").append(storeid);
        sb.append(", storename=").append(storename);
        sb.append(", productid=").append(productid);
        sb.append(", productname=").append(productname);
        sb.append(", contractmoney=").append(contractmoney);
        sb.append(", alreadyperiods=").append(alreadyperiods);
        sb.append(", contractperiods=").append(contractperiods);
        sb.append(", repaymentstartdate=").append(repaymentstartdate);
        sb.append(", repaymentenddate=").append(repaymentenddate);
        sb.append(", repaymentday=").append(repaymentday);
        sb.append(", overduedays=").append(overduedays);
        sb.append(", advancemoney=").append(advancemoney);
        sb.append(", repaymentmoney=").append(repaymentmoney);
        sb.append(", entruststartdate=").append(entruststartdate);
        sb.append(", entrustenddate=").append(entrustenddate);
        sb.append(", entrustcompanyname=").append(entrustcompanyname);
        sb.append(", remarks=").append(remarks);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}